env:
  git_run_number: ${GITHUB_RUN_NUMBER}

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose up
      run: docker compose up -d 
   
    - name: Build the Docker compose ps
      run: docker compose ps
      
    - name: check http response
      run:  echo $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000)
      
    - name: Docker Response
 #     if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}  
         
# #     - name: Build and push
# #      # if:  $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000) == '200'
# #       uses: docker/build-push-action@v2.10.0
   
#     - name: docker build
#       run:  docker build -t saiprakash07/flask:${{ env.git_run_number }} .
      
#     - name: docker image push
# #      if:  $http == '200'
#       run:  docker push saiprakash07/flask:${{ env.git_run_number }} 
      
    - name: dhfh
      run: |
             http_code=$(echo $( curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000 ))
             echo ${http_code}
      
    - name: sdsd
      if:  ${http_code} -eq 200 
      run: echo "Hello Worlds"
     
