env:
  git_run_number: ${GITHUB_RUN_NUMBER}

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose up
      run: docker compose up -d 
   
    - name: Build the Docker compose ps
      run: docker compose ps
      
    - name: check http response
      run:  echo $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000)
      
    - name: Docker Response
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}  
         
      
    - name: wait for webserver to be up
      run: sleep 15
      
    - name: Check HTTP status and push to dockerhub
      run: |
             if [  $(echo $( curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000 )) -eq '200' ]
             then
               echo "hello" 
               docker build -t saiprakash07/flask:${{ env.git_run_number }} .
               docker push saiprakash07/flask:${{ env.git_run_number }} 
               
             else
               echo "HTTP response not 200"
             fi ;
     
